### PR TITLE
WIP: Fix miri errors  (undefined behaviour and data race)

### LINKED ISSUE #3: Undefined Behavior (UB) in `graph.rs`
Running `cargo +nightly miri test`: [Miri](https://github.com/rust-lang/miri)

```rust
running 12 tests
test envelope::tests::test_simple_envelope ... ok
error: Undefined Behavior: trying to retag from <12589981> for SharedReadOnly permission at alloc4083684[0x0], but that tag does not exist in the borrow stack for this location
    --> src\graph.rs:2426:49
     |
2426 |                     let input_values = unsafe { &*output_task.input_buffer_ptr };
     |                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |                                                 |
     |                                                 trying to retag from <12589981> for SharedReadOnly permission at alloc4083684[0x0], but that tag does not exist in the borrow stack for this location
     |                                                 this error occurs as part of retag at alloc4083684[0x0..0x10]
     |
     = help: this indicates a potential bug in the program: it performed an invalid operation, but the Stacked Borrows rules it violated are still experimental
     = help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md for further information
help: <12589981> was created by a SharedReadOnly retag at offsets [0x0..0x10]
    --> src\graph.rs:2149:35
     |
2149 |                 input_buffer_ptr: output_values as *const Box<[Sample]>,
     |                                   ^^^^^^^^^^^^^
help: <12589981> was later invalidated at offsets [0x0..0x10] by a Unique retag
    --> src\graph.rs:2793:42
     |
2793 |             .process(input_buffers, &mut self.output_buffers[..], resources)
     |                                          ^^^^^^^^^^^^^^^^^^^
     = note: BACKTRACE:
     = note: inside `<graph::GraphGen as graph::Gen>::process` at src\graph.rs:2426:49
note: inside `graph::Node::process` at src\graph.rs:2792:9
    --> src\graph.rs:2792:9
     |
2792 | /         self.gen
2793 | |             .process(input_buffers, &mut self.output_buffers[..], resources)
     | |____________________________________________________________________________^
note: inside `graph::tests::changing_the_graph` at src\graph.rs:3349:13
    --> src\graph.rs:3349:13
     |
3349 |             graph_node.process(&null_input(), &mut resources);
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside closure at src\graph.rs:3333:5
    --> src\graph.rs:3333:5
     |
3332 |       #[test]
     |       ------- in this procedural macro expansion
3333 | /     fn changing_the_graph() {
3334 | |         const BLOCK: usize = 1;
3335 | |         let mut graph: Graph = Graph::new(GraphSettings {
3336 | |             block_size: BLOCK,
...    |
3358 | |         }
3359 | |     }
     | |_____^
     = note: this error originates in the attribute macro `test` (in Nightly builds, run with -Z macro-backtrace for more info)

note: some details are omitted, run with `MIRIFLAGS=-Zmiri-backtrace=full` for a verbose backtrace

error: aborting due to previous error

test graph::tests::changing_the_graph ... error: test failed, to rerun pass `--lib`

Caused by:
  process didn't exit successfully: `C:\Users\<USER>\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\bin\cargo-miri.exe runner "C:/Users/<USER>/.cargo/target\miri\x86_64-pc-windows-msvc\debug\deps\knyst-5cf4d8202a729da2.exe"` (exit code: 1)
```

### PR DESCRIPTION
**Pull request by ErikNatanael**
Resolves the errors reported by miri, brought to my attention by @harudagondi. Fixes #3.

### CODE REVIEW

**Comment by harudagondi** [comment]
Btw, I ran miri again, and this leaked memory. Like a lot of memory. I piped the error output into a log file and it is 94669 lines long.

**Comment by harudagondi** [comment]
Here's the interesting part:

`alloc4068091 (Rust heap, size: 98400, align: 8)`

What are you even allocating here? Why is the allocation that big? lol

**Comment by harudagondi** [comment]
There are also a lot of allocations with sizes 512, 3200, 9600, and others.

**Comment by ErikNatanael** [comment]
I saw, haven't gotten to that one yet :)

**Pull request merged**
